/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a document
         * @description Inspect one canonical document and retrieve selected content.
         */
        post: operations["get-document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record feedback
         * @description Persist an agent or evaluation feedback event.
         */
        post: operations["record-feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List uploaded files
         * @description List the organization's uploaded files in its Files knowledge base.
         */
        get: operations["list-files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index uploaded files
         * @description Start an indexing run over the organization's uploaded files so they become searchable in the workspace index. Poll GET /v1/files/index/{sync_id} for progress.
         */
        post: operations["index-files"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/index/{sync_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get indexing run status
         * @description Progress and outcome of one files indexing run.
         */
        get: operations["get-files-index-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a presigned upload URL
         * @description Create a presigned S3 PUT URL for one file. Upload the raw bytes to the returned url with an HTTP PUT and no Authorization header; the body must be exactly the declared size. Then trigger POST /v1/files/index to make the file searchable via /v1/search with scope.indexes ["workspace"].
         */
        post: operations["presign-file-upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an uploaded file
         * @description Delete one uploaded file by name. The document drops out of workspace search after the next indexing run (one is triggered automatically).
         */
        delete: operations["delete-file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's research runs
         * @description Return the caller's research jobs, most recent first. Lightweight: result bodies are omitted (fetch a job by id for its result).
         */
        get: operations["list-research"];
        put?: never;
        /**
         * Start a research run
         * @description Kick off an asynchronous deep-research run and return a job id to poll.
         */
        post: operations["start-research"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/research/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a research run's status and result
         * @description Poll a research job; returns its status, plus the result when completed or the error when failed.
         */
        get: operations["get-research"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Run ranked retrieval over canonical documents and passages.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/{search_id}/integration-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get stored integration results
         * @description Retrieve integration records already acquired during a search without invoking providers again.
         */
        get: operations["get-search-integration-results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Access: {
            rate_limit: components["schemas"]["RateLimit"];
        };
        CaptureHistoryEntry: {
            capture_id: string;
            capture_time: string;
            content_digest: string;
            content_format?: string;
        };
        Citation: {
            /** Format: int64 */
            index: number;
            title: string;
            url: string;
        };
        ContentRange: {
            /** @description Optional capture pin; a stale_range warning is returned when the latest capture differs. */
            capture_id?: string;
            /**
             * Format: int64
             * @description Maximum characters for this range; overrides content.max_chars.
             */
            max_chars?: number;
            /**
             * Format: int64
             * @description Character offset to start content from.
             */
            start_char?: number;
        };
        Document: {
            canonical_url: string;
            content_digest?: string;
            doc_id: string;
            first_seen_at: string;
            headings?: string[] | null;
            last_seen_at: string;
            latest_capture_id?: string;
            meta_description?: string;
            published_at?: string;
            source_url: string;
            title?: string;
        };
        DocumentContent: {
            /** Format: int64 */
            char_count: number;
            format: string;
            selection: string;
            /** Format: int64 */
            start_char?: number;
            text: string;
            truncated: boolean;
        };
        DocumentContentRequest: {
            /**
             * @description Returned content format: markdown (default) preserves document structure (headings, lists, code blocks); text is plain text.
             * @default markdown
             * @enum {string}
             */
            format: "text" | "markdown";
            /** @description When true, passages carry char_start/char_end offsets into the full extracted text when available, for character-precise citation. */
            include_offsets?: boolean;
            /**
             * Format: int64
             * @description Optional maximum content.text characters to return. Omit it for the full selected content. Longer capped reads set content.truncated true; continue with content.range.start_char instead of retrying with a larger cap.
             */
            max_chars?: number;
            /** @description Passage identifiers to return when selection is passage_ids, from a search result's passages or a previous read. */
            passage_ids?: string[] | null;
            /** @description Continuation read: return content starting at a character offset of the same document. */
            range?: components["schemas"]["ContentRange"];
            /**
             * @description How content.text is chosen: full_document (default) returns the extracted document text; query_relevant returns the passages most relevant to query; top_passages returns the document's leading passages; passage_ids returns exactly content.passage_ids; none returns no content body.
             * @default full_document
             * @enum {string}
             */
            selection: "none" | "query_relevant" | "top_passages" | "passage_ids" | "full_document";
        };
        DocumentProvenance: {
            capture_id: string;
            capture_time: string;
        };
        DocumentRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/DocumentRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: uri
             * @description Canonical URL from a result's canonical_url; lookup alternative to doc_id. Either doc_id or canonical_url is required.
             */
            canonical_url?: string;
            /** @description Controls for returned document content: selection strategy, format, size cap, and continuation range. */
            content?: components["schemas"]["DocumentContentRequest"];
            /** @description Reserved for internal evaluation harnesses; ignored for public callers. */
            debug?: {
                [key: string]: unknown;
            };
            /**
             * Format: uuid
             * @description Canonical document identifier (UUID) from a search result's doc_id; stable across searches and recrawls. Either doc_id or canonical_url is required.
             * @example 0c944fa8-4c8f-4f48-9b08-0fb2fd3438ec
             */
            doc_id?: string;
            /** @description Sections to return. Omit it for everything available; otherwise an allowlist of passages, capture_history, and content (document metadata is always returned - send just metadata for a metadata-only read). */
            include?: ("metadata" | "passages" | "capture_history" | "content")[] | null;
            /** @description Query context for passage selection when content.selection is query_relevant. */
            query?: string;
        };
        DocumentResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/DocumentResponse.json
             */
            readonly $schema?: string;
            access: components["schemas"]["Access"];
            capture_history?: components["schemas"]["CaptureHistoryEntry"][] | null;
            content?: components["schemas"]["DocumentContent"];
            doc: components["schemas"]["Document"];
            passages?: components["schemas"]["Passage"][] | null;
            provenance?: components["schemas"]["DocumentProvenance"];
            request_id: string;
            session_id: string;
            usage?: components["schemas"]["Usage"];
            warnings?: components["schemas"]["Warning"][] | null;
        };
        ErrorBody: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Optional structured error details. */
            details?: {
                [key: string]: unknown;
            };
            /** @description Human-readable error message. */
            message: string;
        };
        ErrorEnvelope: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/ErrorEnvelope.json
             */
            readonly $schema?: string;
            /** @description Error details. */
            error: components["schemas"]["ErrorBody"];
            /** @description Server request identifier. */
            request_id: string;
            /**
             * @description Envelope discriminator.
             * @enum {string}
             */
            type: "error";
        };
        FeedbackAgentContext: {
            /** @description Calling model identifier. */
            client_model?: string;
            /** @description Agent task type or evaluation bucket (e.g. 'coding' or 'research'). */
            task_type?: string;
        };
        FeedbackRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FeedbackRequest.json
             */
            readonly $schema?: string;
            /** @description Optional calling-agent context for slicing feedback in evaluation. */
            agent_context?: components["schemas"]["FeedbackAgentContext"];
            /**
             * Format: uuid
             * @description Document the event concerns, from the result's doc_id.
             */
            doc_id?: string;
            /**
             * @description What happened: result_helpful / result_not_helpful (the result did or did not advance the task), passage_used (a passage was used or cited), read_abandoned (opened but abandoned), duplicate_result, stale_result (outdated content), spam_or_low_quality, missing_expected_source (a source you expected did not appear), unsafe_or_policy_issue.
             * @enum {string}
             */
            event_type: "result_helpful" | "result_not_helpful" | "passage_used" | "read_abandoned" | "duplicate_result" | "stale_result" | "spam_or_low_quality" | "missing_expected_source" | "unsafe_or_policy_issue";
            /** @description Free-text context, recorded for human review and offline evaluation. */
            notes?: string;
            /**
             * Format: uuid
             * @description Specific passage the event concerns, from passages[].passage_id; most useful with passage_used.
             */
            passage_id?: string;
            /** @description Query text the event relates to, useful when no search_id is available. */
            query?: string;
            /**
             * Format: int64
             * @description One-based position the result had in the ranked list.
             */
            rank?: number;
            /**
             * Format: uuid
             * @description The search_id returned by /v1/search. Ties feedback to the exact ranked list that produced the result, so ranking learns from the right context.
             */
            search_id?: string;
            /**
             * Format: uuid
             * @description Session the event belongs to (UUID), matching session_id from earlier responses.
             */
            session_id?: string;
        };
        FeedbackResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FeedbackResponse.json
             */
            readonly $schema?: string;
            accepted: boolean;
            access: components["schemas"]["Access"];
            feedback_id: string;
            request_id: string;
            session_id: string;
            usage?: components["schemas"]["Usage"];
        };
        FileDeleteResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FileDeleteResponse.json
             */
            readonly $schema?: string;
            /** @description True when the file was removed. */
            deleted: boolean;
        };
        FileIndexRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FileIndexRequest.json
             */
            readonly $schema?: string;
            /**
             * @description Indexing mode. incremental (default) processes new and changed files; full reprocesses everything.
             * @enum {string}
             */
            mode?: "full" | "incremental";
        };
        FileIndexResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FileIndexResponse.json
             */
            readonly $schema?: string;
            /** @description Initial run state. */
            state: string;
            /** @description Identifier of the accepted indexing run; poll GET /v1/files/index/{sync_id}. */
            sync_id: string;
        };
        FileIndexStats: {
            /**
             * Format: int64
             * @description Bytes fetched.
             */
            bytes: number;
            /**
             * Format: int64
             * @description Documents removed because the object is gone.
             */
            deleted: number;
            /**
             * Format: int64
             * @description Objects discovered.
             */
            enumerated: number;
            /**
             * Format: int64
             * @description Objects that failed processing.
             */
            failed: number;
            /**
             * Format: int64
             * @description Objects downloaded for extraction.
             */
            fetched: number;
            /**
             * Format: int64
             * @description Documents now searchable.
             */
            indexed: number;
            /**
             * Format: int64
             * @description Objects skipped as unsupported types.
             */
            skipped_unsupported: number;
        };
        FileIndexStatusResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FileIndexStatusResponse.json
             */
            readonly $schema?: string;
            /** @description Run completion time (RFC 3339), null while in flight. */
            completed_at: string | null;
            /** @description Terminal error detail, null while healthy. */
            error: string | null;
            /** @description Run start time (RFC 3339), null before it starts. */
            started_at: string | null;
            /** @description Run state (queued, planning, running, completed, failed, …). */
            state: string;
            /** @description Progress counters. */
            stats: components["schemas"]["FileIndexStats"];
            /** @description Indexing run identifier. */
            sync_id: string;
        };
        FileListResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FileListResponse.json
             */
            readonly $schema?: string;
            /** @description The organization's uploaded files, newest first. */
            files: components["schemas"]["FileSummary"][] | null;
        };
        FilePresignRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FilePresignRequest.json
             */
            readonly $schema?: string;
            /** @description Optional MIME type recorded on the object. */
            content_type?: string;
            /** @description Filename to upload. Sanitized server-side; the response echoes the stored name. */
            filename: string;
            /**
             * Format: int64
             * @description Exact file size in bytes. The presigned URL binds this length, so the PUT body must match it.
             */
            size: number;
        };
        FilePresignResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/FilePresignResponse.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Seconds until the presigned URL expires.
             */
            expires_in_seconds: number;
            /**
             * Format: int64
             * @description Per-file upload size limit in bytes.
             */
            max_object_bytes: number;
            /** @description Sanitized filename the upload will be stored and listed under. */
            name: string;
            /** @description Presigned S3 PUT URL. Upload the raw file bytes to this URL with an HTTP PUT (no Authorization header); the body must be exactly the declared size. */
            url: string;
        };
        FileSummary: {
            /** @description Upload time (RFC 3339). */
            last_modified?: string;
            /** @description Filename. */
            name: string;
            /**
             * Format: int64
             * @description Object size in bytes.
             */
            size: number;
        };
        IntegrationResultsResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/IntegrationResultsResponse.json
             */
            readonly $schema?: string;
            access?: components["schemas"]["Access"];
            next_cursor?: string;
            request_id: string;
            results: components["schemas"]["IntegrationSearchResult"][] | null;
            search_id: string;
            /** Format: int64 */
            total: number;
            usage?: components["schemas"]["Usage"];
        };
        IntegrationResultsSummary: {
            href: string;
            /** Format: int64 */
            selected: number;
            /** Format: int64 */
            total: number;
        };
        IntegrationSearchResult: {
            canonical_url: string;
            description?: string;
            doc_id: string;
            index?: string;
            integration: string;
            labels?: string[] | null;
            metadata?: components["schemas"]["SearchResultMetadata"];
            mime?: string;
            operation: string;
            passages?: components["schemas"]["Passage"][] | null;
            /** Format: int64 */
            primary_rank?: number;
            provenance?: components["schemas"]["DocumentProvenance"];
            /** Format: int64 */
            rank: number;
            score?: components["schemas"]["SearchScore"];
            selected: boolean;
            snippet?: string;
            source_uri?: string;
            source_url?: string;
            title?: string;
        };
        Passage: {
            /** Format: int64 */
            char_end?: number;
            /** Format: int64 */
            char_start?: number;
            doc_id: string;
            /** Format: int64 */
            ordinal: number;
            passage_id: string;
            section_heading?: string;
            section_path?: string[] | null;
            text: string;
        };
        Ranking: {
            ranker_version: string;
            score_scope: string;
        };
        RateLimit: {
            /** Format: int64 */
            limit_rps: number;
            /** Format: int64 */
            remaining: number;
            reset_at: string;
        };
        ResearchJobResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/ResearchJobResponse.json
             */
            readonly $schema?: string;
            access?: components["schemas"]["Access"];
            completed_at?: string;
            created_at: string;
            /** @description Present when status is failed. */
            error?: string;
            id: string;
            request_id: string;
            /** @description Present when status is completed. */
            result?: components["schemas"]["ResearchResultResponse"];
            /** @description queued, running, completed, or failed. */
            status: string;
        };
        ResearchJobSummary: {
            completed_at?: string;
            created_at: string;
            id: string;
            query: string;
            /** @description queued, running, completed, or failed. */
            status: string;
        };
        ResearchListResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/ResearchListResponse.json
             */
            readonly $schema?: string;
            access?: components["schemas"]["Access"];
            jobs: components["schemas"]["ResearchJobSummary"][] | null;
            request_id: string;
        };
        ResearchRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/ResearchRequest.json
             */
            readonly $schema?: string;
            /** @description Domains to drop from results. */
            excluded_domains?: string[] | null;
            /**
             * Format: int64
             * @description Max tool calls (web_search/web_read/scratchpad) before a final answer is forced. Optional; defaults internally. The agent usually stops earlier on its own.
             */
            max_tool_calls?: number;
            /** @description Research question to investigate. */
            query: string;
            /**
             * Format: int64
             * @description Per-source fetch timeout in seconds.
             */
            source_timeout?: number;
        };
        ResearchResultResponse: {
            citations: components["schemas"]["Citation"][] | null;
            confidence: string;
            content: string;
            failure_tool?: string;
            /** Format: int64 */
            failure_turn?: number;
            /** Format: int64 */
            llm_calls: number;
            query: string;
            /** Format: int64 */
            read_count: number;
            run_id?: string;
            /** Format: int64 */
            tool_calls_used: number;
            tool_invocations?: components["schemas"]["ToolInvocation"][] | null;
        };
        ResearchStartResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/ResearchStartResponse.json
             */
            readonly $schema?: string;
            access?: components["schemas"]["Access"];
            /** @description Job id to poll at GET /v1/research/{id}. */
            id: string;
            request_id: string;
            status: string;
        };
        ResponseBudget: {
            /**
             * Format: int64
             * @description Maximum serialized response size in characters (roughly 4 characters per token, so 2000 is about 500 tokens).
             */
            max_chars_total?: number;
            /**
             * @description What to do when the budget binds: shed (default) trims in a fixed order - passages, snippet tails, preset extras, then tail results, never below one result - and sets truncated plus a response_truncated warning; error fails with response_too_large instead.
             * @default shed
             * @enum {string}
             */
            on_exceed: "shed" | "error";
        };
        ResponseShape: {
            /** @description Total serialized response budget in characters with deterministic shedding. */
            budget?: components["schemas"]["ResponseBudget"];
            /**
             * @description Field preset: ids_only (rank, doc_id, url, title), compact (adds snippet, score, key dates), standard (today's default), full (adds provenance).
             * @default standard
             * @enum {string}
             */
            verbosity: "ids_only" | "compact" | "standard" | "full";
        };
        SearchRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/SearchRequest.json
             */
            readonly $schema?: string;
            /** @description Calling model identifier, recorded for analytics and ranking tuning. */
            client_model?: string;
            /** @description Structured filters. Keys: country (two-letter code such as 'us' or 'de', scoping results to a market), language (two-letter code such as 'en'), exact_match (boolean; quotes the query so the index matches it verbatim). */
            filters?: {
                [key: string]: unknown;
            };
            /** @description Recency requirements. Keys: published_after (RFC 3339 timestamp or YYYY-MM-DD date; only content published after it) and freshness (coarse window code pd, pw, pm, or py for past day, week, month, or year; ignored when published_after is set). */
            freshness_policy?: {
                [key: string]: unknown;
            };
            /**
             * Format: int64
             * @description Maximum number of ranked results to return. The response carries fewer when the index has fewer matches.
             * @default 10
             */
            max_results: number;
            /**
             * @description The search query, phrased as the user or agent would ask it. Drives ranking and passage selection even when search_queries supplies a rewrite.
             * @example linux kernel amd gpu suspend
             */
            query: string;
            /** @description Optional response shaping: verbosity preset and serialized-size budget. */
            response?: components["schemas"]["ResponseShape"];
            /** @description Which indexes to search. Omit it for the web index. Additive: existing clients are unaffected. */
            scope?: components["schemas"]["SearchScope"];
            /** @description Caller-provided query rewrites. The first entry replaces query as the text sent to the search index; query still drives reranking and passage selection. All entries are visible to the server-side query rewriter. */
            search_queries?: string[] | null;
            /**
             * Format: uuid
             * @description Client session identifier (UUID). Groups related search, document, and feedback calls; equivalent to the X-Session-ID header. When omitted, the server generates one and echoes it back as session_id.
             */
            session_id?: string;
            /** @description Domain allow/deny policy. Keys: include_domains (array of domains; with require_domain_match true, results outside them are dropped, and a single entry is also sent to the index as a site: operator), exclude_domains (array of domains whose results are always dropped), require_domain_match (boolean). Domains match their subdomains; a leading www. is ignored. */
            source_policy?: {
                [key: string]: unknown;
            };
        };
        SearchResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://alpha.api.trycaesar.com/SearchResponse.json
             */
            readonly $schema?: string;
            access?: components["schemas"]["Access"];
            integration_results?: components["schemas"]["IntegrationResultsSummary"];
            ranking?: components["schemas"]["Ranking"];
            request_id: string;
            results: components["schemas"]["SearchResult"][] | null;
            search_id: string;
            session_id: string;
            truncated?: boolean;
            usage?: components["schemas"]["Usage"];
            warnings?: components["schemas"]["Warning"][] | null;
        };
        SearchResult: {
            canonical_url: string;
            description?: string;
            doc_id: string;
            index?: string;
            labels?: string[] | null;
            metadata?: components["schemas"]["SearchResultMetadata"];
            mime?: string;
            passages?: components["schemas"]["Passage"][] | null;
            provenance?: components["schemas"]["DocumentProvenance"];
            /** Format: int64 */
            rank: number;
            score?: components["schemas"]["SearchScore"];
            snippet?: string;
            source_uri?: string;
            source_url?: string;
            title?: string;
        };
        SearchResultMetadata: {
            content_digest?: string;
            extracted_at?: string;
            first_seen_at?: string;
            last_crawled_at?: string;
            last_seen_at?: string;
            published_at?: string;
        };
        SearchScope: {
            /** @description Indexes to search: web (the shared web corpus) and/or workspace (your organization's ingested documents). Default: ["web"]. */
            indexes?: string[] | null;
            /**
             * Format: uuid
             * @description Workspace to search; required when indexes includes workspace.
             */
            workspace_id?: string;
        };
        SearchScore: {
            /** Format: double */
            value: number;
        };
        ToolInvocation: {
            error?: string;
            /** Format: int64 */
            latency_ms: number;
            /** Format: int64 */
            ordinal: number;
            query?: string;
            /** Format: int64 */
            result_count: number;
            status: string;
            tool: string;
            /** Format: int64 */
            turn: number;
            url?: string;
        };
        Usage: {
            /** Format: int64 */
            bytes_returned: number;
            /** Format: int64 */
            requests: number;
        };
        Warning: {
            code: string;
            details?: {
                [key: string]: unknown;
            };
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-document": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            /** @description Document payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Insufficient prepaid balance. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Document not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search infrastructure unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search infrastructure unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "record-feedback": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search or document target not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uploaded files. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File service unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File endpoints are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "index-files": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileIndexRequest"];
            };
        };
        responses: {
            /** @description Indexing run accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileIndexResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File service unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File endpoints or indexing are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-files-index-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Indexing run identifier returned by POST /v1/files/index. */
                sync_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexing run status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileIndexStatusResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Indexing run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File service unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File endpoints are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "presign-file-upload": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilePresignRequest"];
            };
        };
        responses: {
            /** @description Presigned upload URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePresignResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File exceeds the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported file type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File service unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File endpoints are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "delete-file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Filename to delete, as returned by GET /v1/files. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDeleteResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File service unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description File endpoints are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "list-research": {
        parameters: {
            query?: {
                /** @description Max jobs to return (default 50, max 200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Research jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchListResponse"];
                };
            };
            /** @description Invalid API key, or missing API key when keyless access is disabled. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "start-research": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Research run accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStartResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid API key, or missing API key when keyless access is disabled. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Insufficient prepaid balance. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited, or too many concurrent research jobs. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-research": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Research job id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Research job status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchJobResponse"];
                };
            };
            /** @description Invalid API key, or missing API key when keyless access is disabled. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Research job not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client session identifier. */
                "X-Session-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Insufficient prepaid balance. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search infrastructure unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search infrastructure unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    "get-search-integration-results": {
        parameters: {
            query?: {
                /** @description Maximum results in this page. */
                limit?: number;
                /** @description Opaque cursor returned by the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Search identifier returned by POST /v1/search. */
                search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored integration results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResultsResponse"];
                };
            };
            /** @description Invalid limit or cursor. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API key does not have the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Search not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Stored integration results are unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
